### ISSUE TITLE
[Social] Twitter: unable to render Card preview

### ISSUE THREAD

**Issue by kptdobe** [adobe/blog#103]
Twitter is unable to render card preview.

Open https://cards-dev.twitter.com/validator and enter an article url: 

```
INFO:  Page fetched successfully
INFO:  17 metatags were found
ERROR: No card found (Card error)
```

**Comment by zubin-madon** [comment]
> Twitter is unable to render card preview.
> 
> Open https://cards-dev.twitter.com/validator and enter an article url:
> 
> ```
> INFO:  Page fetched successfully
> INFO:  17 metatags were found
> ERROR: No card found (Card error)
> ```

I'm having this exact same issue and my metatags are fine. They're the same as my other working sites. I'm trying in a NextJS app. #104 isn't helping me.

**Comment by Reseachershan** [comment]
> > Twitter is unable to render card preview.
> > Open https://cards-dev.twitter.com/validator and enter an article url:
> > ```
> > INFO:  Page fetched successfully
> > INFO:  17 metatags were found
> > ERROR: No card found (Card error)
> > ```
> 
> I'm having this exact same issue and my metatags are fine. They're the same as my other working sites. I'm trying in a NextJS app. #104 isn't helping me.

you should use 'open graph protocol' for having twitter card and on any social media
