### ISSUE TITLE
Sitemap: why sitemap-index.xml ?

### ISSUE THREAD

**Issue by kptdobe** [adobe/blog#138]
https://blog.adobe.com/sitemap.xml does not exist but https://blog.adobe.com/sitemap-index.xml does (source file is https://github.com/adobe/blog/blob/main/sitemap-index.xml).

@dominique-pfister is there any specific reason for that ? Why not using standard `sitemap.xml` name ?

**Comment by dominique-pfister** [comment]
Funny, looking at the commit history of that file in GitHub, it was you that created it (comment: `chore: initial business site copy`). I know that there are certain naming restrictions for other sites (e.g. express-website), but AFAICT there is none for blog.adobe.com. 

Some people might prefer `-index` in the name when it is a `sitemapIndex` in the document (as opposed to a simple sitemap). I'm wondering what @rofe and @davidnuescheler have to say about this...

**Comment by rofe** [comment]
@kptdobe I think this was changed on purpose: as @dominique-pfister pointed out, the file is a sitemap index, hence the explicit file name. However, the [robots.txt](https://blog.adobe.com/robots.txt) does not reference the sitemap index, but instead the full list of language-based sitemaps, and I think that's probably wrong: either the robots.txt should reference the sitemap-index.xml, or we should delete the latter. Unless of course it has been submitted to Google via Seacr Console, which I don't know.

@davidnuescheler wdyt?
