### ISSUE TITLE
[Sidekick] Migrate from theblog

### ISSUE THREAD

**Issue by kptdobe** [adobe/blog#45]
Theblog sidekick has plenty of features that need to be ported into the new code base. See https://github.com/adobe/theblog/blob/master/tools/sidekick/config.js

**Comment by kptdobe** [comment]
> Remove sidekick overrides adding `.html` back

This is referenced in the Migration plan, we should probably tackle that together.

**Comment by rofe** [comment]
@kptdobe
> Remove sidekick overrides adding .html back

👍 

There are 2 more customizations in the `theblog` sidekick:
- add `/publish/` back if missing -> this could be redirected at the CDN level
- add `_` in `*/_taxonomy.json` back after fetching the status on `_taxonomy.xlsx` -> this could easily be avoided by removing the `_` from the Excel filename

**Comment by kptdobe** [comment]
>  this could easily be avoided by removing the _ from the Excel filename

Good point. Done.
