### ISSUE TITLE
[Publication] Daily auto-publish must be configured

### ISSUE THREAD

**Issue by kptdobe** [adobe/blog#47]
Everyday, the content is auto published. This requires some configuration in the query-index AND the new coming "crontab" feature https://github.com/adobe/helix-slack-bot/issues/249.
Publication times must be aligned with the current ones.

- [x] en
- [x] ko
- [ ] ~~jp~~
- [ ] ~~it~~
- [x] fr
- [ ] ~~es~~
- [ ] ~~de~~
- [ ] ~~br~~

@dominique-pfister Can you help here too ?

**Comment by dominique-pfister** [comment]
Please elaborate how auto publish is expected to do:
- should it take the pattern for that day (e.g. 2021-11-01) and **actually** publish those pages?
- or should the pages already "be there" and just the index updated at the designated time?

**Comment by kptdobe** [comment]
Good point. Probably more complicated that initially thought.

I see to variables:
- the time configured in the query-index which defines "when is the beginning of the day for a region" - i.e. when articles go from `raw-index` to `helix-default` sheets
- some timer that publish the index automatically "at the beginning of the day of a region"

Today, if author did not hit publish, it still works. It will not anymore.

I suggest that we start simple, i.e. just update the index at a given time every day for each region. If articles are missing frequently, we could considering adding more magic.

WDYT ?

**Comment by dominique-pfister** [comment]
Sounds good, that should be easily doable.

**Comment by rofe** [comment]
@dominique-pfister we currently only automate `en` and `ko`, while the rest of the regions is publishing manually, right? We should keep that the same.

**Comment by dominique-pfister** [comment]
Roger that

**Comment by dominique-pfister** [comment]
Prepared switch in our Google Apps Script to invoke publish index at the designated times. Next, they will automatically be invoked by Scheduled Publishing.

**Comment by kptdobe** [comment]
The scheduling worked yesterday. Closing issue.
