### ISSUE TITLE
[Go-Live] blog.adobe.com to hlx3 - change the edge DNS config

### ISSUE THREAD

**Issue by kptdobe** [adobe/blog#50]
What needs to happen here is not fully clear to me - I assume Go to Fastly and edit "blog.adobe.com" service backend url: change from `theblog--adobe.hlx.page` to `main--blog--adobe.hlx3.page`.

@tripodsan @stefan-guggisberg @trieloff @rofe @davidnuescheler : is this really the only thing needed ?

This depends also from #49.

**Comment by trieloff** [comment]
Almost. We also need to change the backend `Host` header in the same settings screen.

**Comment by rofe** [comment]
Except we won't do this in the `blog.adobe.com` Fastly service (Skyline), but in `theblog--adobe.hlx.live`.

**Comment by stefan-guggisberg** [comment]
I've prepared `theblog--adobe.hlx.live` draft version 146 for the hlx3 switch.

**Comment by stefan-guggisberg** [comment]
you can use https://test--blog--adobe.hlx.live/ for testing.

**Comment by kptdobe** [comment]
Go-live done.
