### ISSUE TITLE
Resubmit sitemap with the new extensionless canonicals

### ISSUE THREAD

**Issue by kptdobe** [adobe/blog#52]
With the hlx3 migration, we are getting rid of the `.html` in the urls (see #7). Sitemap will be re-generated and will not contain the extensions (see #46).

Once the site will be migrated and the sitemaps will be regenerated, we will need to re-submit them to Google. 
We need to find who has access to do so.

**Comment by rofe** [comment]
> We need to find who has access to do so.

I do
