### ISSUE TITLE
[UI] gnav does not look like the original

### ISSUE THREAD

**Issue by kptdobe** [adobe/blog#55]
Current gnav on https://blog.adobe.com:

![image](https://user-images.githubusercontent.com/474200/139831428-f72733ea-2298-4ef4-ac1c-6cfa8da633eb.png)

Our gnav on https://main--blog--adobe.hlx3.page/

![image](https://user-images.githubusercontent.com/474200/139831476-8ee03d68-9fa2-45dc-a195-d874b98fd99c.png)

- [ ] box size is smaller
- [ ] overall spacing is missing
- [ ] promo background should be white
- [ ] promo link should be left align
- [ ] mobile version looks broken

@auniverseaway any chance you could take a look at this one "quickly" ? Go-Live date for the blog is Nov 9.

**Comment by kptdobe** [comment]
It is even worst on mobile:

![image](https://user-images.githubusercontent.com/474200/139833764-7c080959-a4c7-4c00-b633-7e40284acce1.png)

**Comment by auniverseaway** [comment]
@kptdobe Couple notes:

The over-arching thing I'm seeing is that the new gnav follows newer conventions... spacing, search fields, etc. I've attached the current spec. As you can see, blog is out of date. Especially around the profile, search, adobe icons. Same with the search field, the old does not come close to matching the proper [Spectrum search field](https://opensource.adobe.com/spectrum-css/search.html#standard). For menus, neither nav is accurate.

![xxp4_09rkN7B40PJwOk9cg](https://user-images.githubusercontent.com/1972095/139917893-9d04fac3-2c9b-44c7-a2e6-48bfcab04e28.png)
![rFOJURYgqIafTAvb-fXA2g](https://user-images.githubusercontent.com/1972095/139919337-fc2165a0-63f6-42d6-a976-2681b9769d20.jpg)
If you just want the blog to look the _exact same_ as before, I think you'll have to maintain that in this project. The gnav I built is meant to follow current adobe.com / Consonant / Spectrum practices. You can also continue shipping the old gnav if you prefer until this is where you want it to be.

**That being said, there's some things I'll address:**
1. I'll send a PR for menu & promo. I do think it's the consumers responsibility to support whatever promo styles they have. We should not be shipping every promo permutation.
2. I'll send a PR for mobile. We don't have an official spec, but I can definitely improve the sub menus to make them a bit more polished. Keep in mind, they will still be made to better match adobe.com / Consonant and not the existing blog.
3. There's a whole new search experience built by @davidnuescheler that is much more contextually relevant. The new gnav search experience better matches Spectrum's search field as well. If you're looking for the old search, you'd have to build something.

Next time let me know you're going to pull something off business, I could have offered some context.

**Comment by rofe** [comment]
Thanks @auniverseaway for the added context and upcoming tweaks

In my opinion, the blog gnav look & feel should be updated to match whatever is the most current in the a.com realm. There's nothing to be gained in attempting to copy the old gnav. And regarding, the old search, I think we want to be as far away as possible from that 😉

**Comment by kptdobe** [comment]
I fully agree this should follow the new specs and not try to copy the old one.
Thanks a lot @auniverseaway for the upcoming PRs.
