### ISSUE TITLE
Javascript error and "broken" layout with side-by-side images

### ISSUE THREAD

**Issue by kptdobe** [adobe/blog#56]
Open https://main--blog--adobe.hlx3.page/en/publish/2021/04/22/photoshop-and-adobe-experience-manager-accelerating-creativity-through-apis

Check the Javascript error:

```
Auto Blocking failed TypeError: Cannot read properties of null (reading 'insertBefore')
    at scripts.js:537
    at Array.forEach (<anonymous>)
    at buildImageBlocks (scripts.js:532)
    at buildAutoBlocks (scripts.js:654)
    at decorateMain (scripts.js:975)
    at loadEager (scripts.js:1081)
    at decoratePage (scripts.js:1158)
    at scripts.js:1163
```

This is cause by the 2 side-by-side images (the phone screenshots) in the source document. They do not end-up in a block.

This was somehow supported on the hl2 version: https://blog.adobe.com/en/publish/2021/04/22/photoshop-and-adobe-experience-manager-accelerating-creativity-through-apis.html:

![image](https://user-images.githubusercontent.com/474200/139839755-f85a7f63-84e6-431b-9c85-649482c0046d.png)

At least, there should not be an error.

**Comment by rofe** [comment]
Reopening because I didn't like my initial brute-force approach. I wanted to create a "real" side-by-side images block instead.
