### ISSUE TITLE
LATAM landingpage is empty

### ISSUE THREAD

**Issue by kptdobe** [adobe/blog#61]
Open https://main--blog--adobe.hlx3.page/es/latam
No articles.
But https://main--blog--adobe.hlx3.page/es/publish/2021/02/18/5-ideas-creativas-con-photoshop is tagged with LATAM. It should be visible on the latam page.

**Comment by fkakatie** [comment]
As far as I can tell, the previous version of the blog built the article feed WITHOUT checking against taxonomy (https://github.com/adobe/theblog/blob/385aee8ac5f776c4b153ad1804c4fc7548610844/scripts/v2/common.js#L430). 

New blog checks that the tag exists on the post _and_ in the taxonomy (https://github.com/adobe/blog/blob/cfe03c223dde7dbb9b7b11b925bec59a7e670693/blocks/article-feed/article-feed.js#L297).

Am I reading this correctly? Should this check against the taxonomy be omitted?

**Comment by kptdobe** [comment]
Thank for checking. The LATAM tag was obviously missing in the taxonomy! I have added it, this fixed the issue.
