### ISSUE TITLE
Handle .html vs no .html

### ISSUE THREAD

**Issue by kptdobe** [adobe/blog#7]
Current link to articles in content, especially in promotions, featured / recommended articles contains `.html`. But requesting an article with a `.html` returns a 404.
While there is some thing that needs to happen globally, while we import the content, we can certainly remove the `.html`.
Also, we could add client side logic to remove it.

**Comment by kptdobe** [comment]
@stefan-guggisberg will you be able to take care of this ?

**Comment by rofe** [comment]
@kptdobe as mentioned [above](https://github.com/adobe/blog/issues/7#issuecomment-944268128), the redirect should be generic rather than per URL.

**Comment by stefan-guggisberg** [comment]
> @stefan-guggisberg will you be able to take care of this ?

@kptdobe yes, I can configure a generic `/*.html` -> `/*` redirect. when should the generic redirect be active?

> Related: we'll need to resubmit a sitemap with the new extensionless canonicals...

Who's in charge for this?

**Comment by kptdobe** [comment]
> I can configure a generic /*.html -> /* redirect. when should the generic redirect be active?
I assume that as soon as we go-live, there will be tons of requests coming-in with the extension. I think it should be there when we change the backend url to adobe/blog.

> Related: we'll need to resubmit a sitemap with the new extensionless canonicals...
> Who's in charge for this?
I have created https://github.com/adobe/blog/issues/52 to track this.

**Comment by stefan-guggisberg** [comment]
I have prepared a generic `/x.html` -> `/x` redirect in draft version 146, together with other changes for the hlx3 switch.

**Comment by kptdobe** [comment]
Brilliantly handled by @stefan-guggisberg. Closing now.
